server:
  port: ${ORDER_SERVICE_PORT:8083}

spring:
  config:
    import:
      - optional:file:../../.env[.properties]
      - optional:file:.env[.properties]
  application:
    name: order-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/order_service?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:ASDF1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
  internal:
    secret: ${APP_INTERNAL_SECRET:12345}
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:booknest.events}
    notification-routing-key: ${RABBITMQ_NOTIFICATION_ROUTING_KEY:notification.events}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
services:
  cart:
    url: ${CART_SERVICE_URL:http://localhost:8082}
  book:
    url: ${BOOK_SERVICE_URL:http://localhost:8081}
  wallet:
    url: ${WALLET_SERVICE_URL:http://localhost:8084}
  order:
    cod:
      enabled: true
    max-quantity-per-item: 10
