server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # ✅ Add globalcors here
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      # ✅ Add this — removes duplicate CORS headers
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # 1.auth-service routes (public)
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: auth-oauth-service
          uri: lb://auth-service
          predicates:
            - Path=/oauth2/**,/login/**

        # 2.cart-service routes (protected)
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**

        # 3.order-service routes (protected)
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

        # 4.wallet-service
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallet/**

        # 5.review-service
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**

        # 6.notification-service routes (protected)
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

        #7.whishlist-service routes
        - id: wishlist-service
          uri: lb://wishlist-service
          predicates:
          - Path=/api/wishlist/**

        #.book-service routes
        - id: book-service
          uri: lb://book-service
          predicates:
              - Path=/api/books/**


app:
  jwt:
    secret: bXlTZWNyZXRLZXlGb3JKV1RNYWtlSXRMb25nRW5vdWdoMjU2Qml0cyEh
    expiration: 86400000
  internal:              # ✅ internal is under app, NOT under jwt
    secret: 12345
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:            # ← under eureka
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
reactor:
  netty:
    pool:
      maxIdleTime: 20000
